### PR TITLE
Haiku support in dotnet/arcade

### PR DESCRIPTION
**Pull request by trungnt2910**
### To double check:

* [x] The right tests are in and and the right validation has happened.  Guidance:  https://github.com/dotnet/arcade/tree/main/Documentation/Validation

(I hope so?)

These are the changes that should be merged to dotnet/arcade.

Because many of these is your work and you mentioned that you want to upstream this yourself, I'm opening a pull request here (instead of directly in dotnet).

With [krb5](http://github.com/haikuports/haikuports/pull/7009/) already on [HaikuDepot](https://depot.haiku-os.org/#!/pkg/krb5/haikuports/haikuports_x86_64/1/20/-/-/1/x86_64?bcguid=bc173-XONW)  `build-rootfs.sh` should work properly.

### CODE REVIEW

**Comment by trungnt2910** [comment]
This pull request is currently blocked by [this](https://github.com/haikuports/haikuports/pull/7036) pull request to HaikuPorts.

**Comment by trungnt2910** [comment]
Or maybe [this](https://github.com/haikuports/haikuports/pull/7045) pull request to HaikuPorts.

When either one of them gets merge, work on this can continue.

**Comment by trungnt2910** [comment]
libroot unwind hack by x512 has been dropped, and replaced by `llvm_libunwind` package from HaikuPorts.
build-rootfs.sh has been tested and working on Linux.

**Comment by trungnt2910** [comment]
Toolchain for Haiku is working.

This is a version taken from your fork of dotnet-runtime, but with a little bit of cleaning up.
I've pushed some other misc cmake changes to the other repo, related to Haiku's libunwind detection, but the changes there should not affect this pull request.

**Comment by jessicah** [comment]
Is https://github.com/jessicah/dotnet-runtime/commit/58903ab32f029894202115f6d52f56ec8e01478b not needed anymore?

**Comment by trungnt2910** [comment]
No, it's not needed. We can use [find_path](https://www.haiku-os.org/docs/api/group__libroot.html#gad7aea8c7f59a75196467df38f9c5635a) instead.

**Comment by jessicah** [comment]
PR to dotnet/arcade: https://github.com/dotnet/arcade/pull/10066

**Pull request closed without merging**
